---
title: "Penentuan Faktor Pertumbuhan Anak"
author: "Jehuda Rivaldo S. (160419133), Kenneth Manuel Lieyanto (160419041)"
date: "5/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Library
library(readxl)
library(psych)
```

```{r}
#Baca data 
data <- read_excel("Tugas FA  - WiscsemData.xlsx")
head(data)
str(data)
#ada 241 data dari client,	agemate,	info,	comp,	arith,	simil,	vocab,	digit,	pictcomp,	parang,	block,	object,	coding

```

```{r}
#buat matriks eigen, vector dari data 
data_matriks <- as.matrix(data)
data_matriks_korelasi <- cor(data_matriks)
data_matriks_eigen <- eigen(data_matriks_korelasi)
data_matriks_vektor <- data_matriks_eigen$vectors
data_matriks_vektor_transpose <- t(data_matriks_vektor)
data_matriks_vektor %*% data_matriks_vektor_transpose
```

```{r}
#mengambil 3 sampel eigen vektor
eigen_vektor <- data_matriks_vektor[,1:3]
eigen_vektor
```

```{r}
#membuat matriks diagonal
matriks_diagonal <- data_matriks_eigen$values[1:3]
matriks_diagonal_value <- diag(matriks_diagonal, 3,3)
```

```{r}
#membuat load faktor
load_factor <- eigen_vektor %*% sqrt(matriks_diagonal_value)
load_factor
```

```{r}
#membuat matriks invers
data_matriks_korelasi_invers <- solve(data_matriks_korelasi)
```

```{r}
load_factor_rotate <- varimax(load_factor)
plot(load_factor_rotate$loadings[,1:2], type = "n")
#plot(load_factor_rotate$loadings[,1:2], labels=names(data), cex = 1)
```

```{r}

```
